const EASYMAP = {
  width: 7,
  height: 7,
  blackTiles: [
    { x: 3, y: 0, number: 1 },
    { x: 1, y: 1, number: 0 },
    { x: 5, y: 1, number: 2 },
    { x: 0, y: 3, number: null },
    { x: 3, y: 3, number: null },
    { x: 6, y: 3, number: null },
    { x: 1, y: 5, number: null },
    { x: 5, y: 5, number: 2 },
    { x: 3, y: 6, number: 3 },
  ],
  bulbs: [],
};
const EASYMAP_SOLUTION = [
  { x: 0, y: 0 },
  { x: 0, y: 5 },
  { x: 1, y: 3 },
  { x: 2, y: 6 },
  { x: 3, y: 1 },
  { x: 3, y: 5 },
  { x: 4, y: 6 },
  { x: 5, y: 0 },
  { x: 5, y: 4 },
  { x: 6, y: 1 },
  { x: 6, y: 5 },
];

const ADVANCED_MAP = {
  width: 7,
  height: 7,
  blackTiles: [
    { x: 2, y: 0, number: 0 },
    { x: 4, y: 0, number: null },
    { x: 0, y: 2, number: null },
    { x: 2, y: 2, number: null },
    { x: 4, y: 2, number: 3 },
    { x: 6, y: 2, number: null },
    { x: 3, y: 3, number: 1 },
    { x: 0, y: 4, number: 2 },
    { x: 2, y: 4, number: null },
    { x: 4, y: 4, number: null },
    { x: 6, y: 4, number: null },
    { x: 2, y: 6, number: null },
    { x: 4, y: 6, number: 2 },
  ],
  bulbs: [],
};
const ADVANCED_MAP_SOLUTION = [
  { x: 0, y: 0 },
  { x: 6, y: 0 },
  { x: 4, y: 1 },
  { x: 3, y: 2 },
  { x: 5, y: 2 },
  { x: 0, y: 3 },
  { x: 6, y: 3 },
  { x: 1, y: 4 },
  { x: 4, y: 5 },
  { x: 0, y: 6 },
  { x: 3, y: 6 },
  { x: 6, y: 6 },
];
const EXTREME_MAP_SOLUTION = [
  { x: 5, y: 0 },
  { x: 4, y: 1 },
  { x: 6, y: 1 },
  { x: 8, y: 1 },
  { x: 3, y: 3 },
  { x: 5, y: 3 },
  { x: 2, y: 4 },
  { x: 7, y: 5 },
  { x: 9, y: 5 },
  { x: 4, y: 6 },
  { x: 8, y: 6 },
  { x: 0, y: 7 },
  { x: 3, y: 7 },
  { x: 1, y: 8 },
  { x: 6, y: 8 },
  { x: 0, y: 9 },
];
const EXTREME_MAP = {
  width: 10,
  height: 10,
  blackTiles: [
    { x: 1, y: 0, number: null },
    { x: 5, y: 1, number: 3 },
    { x: 7, y: 1, number: 2 },
    { x: 9, y: 1, number: null },
    { x: 1, y: 2, number: 0 },
    { x: 2, y: 2, number: null },
    { x: 7, y: 2, number: null },
    { x: 4, y: 3, number: null },
    { x: 1, y: 4, number: 1 },
    { x: 4, y: 4, number: null },
    { x: 5, y: 4, number: 1 },
    { x: 6, y: 4, number: null },
    { x: 3, y: 5, number: null },
    { x: 4, y: 5, number: null },
    { x: 5, y: 5, number: null },
    { x: 8, y: 5, number: 3 },
    { x: 5, y: 6, number: null },
    { x: 2, y: 7, number: 1 },
    { x: 7, y: 7, number: 0 },
    { x: 8, y: 7, number: null },
    { x: 0, y: 8, number: 3 },
    { x: 2, y: 8, number: null },
    { x: 4, y: 8, number: 0 },
    { x: 8, y: 9, number: 0 },
  ],
  bulbs: [],
};

const prevResults = permaLoadJSON('prevResults')
